########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

# Use the Kit Template repo configuration as a base. Only override things specific to the repo.
import_configs = [
    "${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml",
    "${root}/_repo/deps/repo_kit_tools/kit-template/repo-app.toml"
]

# Repository Name
name = "lp.omniscripts"

[repo_kit_link_app]
app_name = ""   # App name.
app_version = ""    # App version. Empty means latest. Specify to lock version, e.g. "2022.2.0-rc.3"


########################################################################################################################
# Documentation building
########################################################################################################################

[repo_docs]
#name = "Kit App Template"

# kit-manual doc
[[repo_docs.kit.custom_project]]
name = "lp.omniscripts"
root = "${root}"
config_path = "${root}/docs/docs.toml"


[repo_docs.kit]
extensions = [
]

